---
title: "Simulation figures"
author: "Hanne Oberman"
date: "7-10-2021"
output: html_document
---

```{r setup, include=FALSE}
# packages
library(dplyr)
library(ggplot2)

# load simulation output
results <- readRDS("Data/output.RDS")$results
# results <- readRDS("output.RDS") %>% .$results %>% purrr::map_dfr(., ~{.x %>% .[1:20000, ] %>% tidyr::pivot_longer(cols = everything()[-c(1:2)], names_to = "method", values_to = "Y_pred", names_prefix = "Y_pred_")}) %>% cbind(sim = rep(1:1000, each = 20000*8)) %>%  as_tibble()
gc()

# # add surrogate split results from hpc
# results_sur <- readRDS("Results/results_sur_1_to_10.RDS")

# add shortcuts
meth <- names(results[[1]])[c(3:5, 9, 6:8, 10)]
meth_lab <- c("CMI+FLR", "SDI+FLR", "MDI+FLR", "BOS+FLR", "CMI+RF", "SDI+RF", "MDI+RF", "BOS+RF")
meth_col <- c("#1269b0", "#81c454") %>% setNames(c("FLR", "RF"))
pred_lab <- paste0("X", 1:10)
pred_col <- c("#1269b0", "#7c1315") %>% setNames(c("Observed", "Missing"))
```

# Visualize DGM

## Variables

```{r dgm}
# load data and names
dgm <- readRDS("Data/output.RDS") %>% .$DGM

dgm$varcov %>% 
  cov2cor() %>% 
  ggcorrplot::ggcorrplot(lab = TRUE, type = "upper")

corr <- dgm$varcov %>% 
  cov2cor() %>% 
  cbind(pred_lab, .) %>% 
  as.data.frame() %>% 
  setNames(c("pred", pred_lab)) %>% 
  tidyr::pivot_longer(cols = everything()[-1]) %>% 
  mutate(value = as.numeric(value),
         text = round(value, 2))

corr[corr$pred==corr$name, "value"] <- NA
# corr[corr$pred==corr$name, "text"] <- pred_lab
corr[c(11, 21, 22, 31:33, 41:44, 51:55, 61:66, 71:77, 81:88, 91:99), "value"] <- NA
corr[c(11, 21, 22, 31:33, 41:44, 51:55, 61:66, 71:77, 81:88, 91:99), "text"] <- NA

ggplot(corr, aes(x = pred, y = name, fill = value, label = text)) +
  geom_tile() +
  geom_text() +
  scale_x_discrete(limits = pred_lab) +
  scale_y_discrete(limits = rev(pred_lab)) +
  scale_fill_viridis_c(na.value = 0, alpha = .6, name = "Correlation") +
  labs(x = "", y = "") +
  theme_classic() 

coef <- data.frame(
  value = dgm$betas, 
  pred = factor(pred_lab, levels = pred_lab), 
  type = c(rep("Y", 10), rep("Y*", 10))) %>% 
  mutate(text = round(value, 2))

ggplot(coef, aes(x = pred, y = type, fill = value, label = text)) +
  geom_tile() +
  geom_text() +
  scale_y_discrete(limits = c("Y*", "Y")) +
  scale_fill_viridis_c(na.value = 0, alpha = .6, name = "Coefficient") +
  labs(x = "", y = "") +
  theme_classic() 

```

## Missingness

```{r}
patterns <- tibble(
  rownr = 1:5, 
  X = rep(1, 5), 
  Y = c(1,1,1,0, 0), 
  Z = c(1, rep(0,4))) %>% 
  tidyr::pivot_longer(cols = c(X, Y, Z)) %>%
  mutate(across(everything(), as.factor))

patt <- dgm$miss_pat[c(4,8,12), -c(1:2)] %>% 
  as.data.frame() %>% 
  cbind(row = 1:3, .) %>% 
  tidyr::pivot_longer(cols = everything()[-1]) %>% 
  mutate(value = factor(value, levels = c(0,1), labels = c("Missing", "Observed")))

# patt2 <- dgm$miss_pat[, -c(1:2)] %>% 
#   as.data.frame() %>% 
#   cbind(row = 1:12, 
#         type = c("Left", "Middle", "Right", "Tails"),
#         .)
  
ggplot(patt, aes(x = name, y = row, fill = value)) +
  geom_tile(color = "black") +
  scale_x_discrete(limits = pred_lab) +
  scale_y_discrete(limits = 1:3, labels = paste("Pattern", 3:1)) +
  scale_fill_manual(values = pred_col, name = "Predictor value") +
  labs(x = "", y = "") +
  theme_minimal() 

```


# Visualize results

```{r reference}
# devsets <-readRDS("Data/datasets.RDS") %>% purrr::map("devset")
# reference_performance <- function(devset){
# # flexible logistic regression
# perf_FLR <- devset %>% 
#   cbind(FLR = glm(Y ~ splines::ns(X1, df = 3) + . - X1,
#               family = "binomial",
#               data = .) %>% .$fitted.values)
# cali_FLR <- perf_FLR %>% lm(Y ~ FLR, data = .) %>% .$coefficients
# auc_FLR <- perf_FLR %>% pROC::roc(Y, FLR) %>% .$auc %>% as.numeric()
# # random forest
# perf_RF <- devset %>% 
#   cbind(RF = ranger::ranger(Y ~ ., data = .) %>% .$predictions)
# auc_RF <- perf_RF %>% pROC::roc(Y, RF) %>% .$auc %>% as.numeric()
# cali_RF <- perf_RF %>% lm(Y ~ RF, data = .) %>% .$coefficients
# out <- data.frame(
#   method = c("FLR", "RF"), 
#   intercept = c(cali_FLR[1], cali_RF[1]),
#   slope = c(cali_FLR[2], cali_RF[2]),
#   auc = c(auc_FLR, auc_RF))
# return(out)
# }
# ref_perf <- devsets %>% purrr::map( ~reference_performance(.x))
# saveRDS(ref_perf, file = "Results/reference_performance.RDS")
ref_perf <- readRDS("Results/reference_performance.RDS")
```


## Calibration

```{r calibration}
cali <- purrr::map_dfr(results, function(.i){
  purrr::map_dfr(meth, ~{lm(.i$Y_true ~ .i[ , .x])$coefficients %>% c(analysis = NA, method = .x, .)}) %>% setNames(c("Analysis", "Method", "Intercept", "Slope"))
}) %>% mutate(Analysis = case_when(stringr::str_detect(Method, "log")~"FLR", TRUE~"RF"),
              Intercept = as.numeric(Intercept), 
              Slope = as.numeric(Slope),
              Method = factor(Method, levels = meth, labels = meth_lab, ordered = TRUE)
              )

cali %>% 
  ggplot(aes(x = Method, y = Intercept, fill = Analysis)) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_boxplot() +
  scale_x_discrete(breaks = meth, labels = meth_lab) +
  scale_fill_manual(values = meth_col) +
  theme_classic() 

cali %>% 
  ggplot(aes(x = Method, y = Slope, fill = Analysis)) +
  geom_hline(yintercept = 1, color = "grey") +
  geom_boxplot() +
  scale_x_discrete(breaks = meth, labels = meth_lab) +
  scale_fill_manual(values = meth_col) +
  theme_classic() 

# ggplot(results) +
#   geom_smooth(aes(x = Y_pred, y = Y_prob), method = "lm") +
#   facet_wrap(~method)
```


## RMSE

```{r RMSE}
rmse <- purrr::map_dfr(results, function(.i){purrr::map_dfc(.i[,-c(1:2)], ~{sqrt(mean((.x - .i$Y_prob)^2))})}) %>% 
  tidyr::pivot_longer(cols = everything(), names_to = "Method", values_to = "RMSE") %>% 
  mutate(Analysis = case_when(stringr::str_detect(Method, "log")~"FLR", TRUE~"RF"),
         Method = factor(Method, levels = meth, labels = meth_lab, ordered = TRUE)
        )

rmse %>% 
  ggplot(aes(x = Method, y = RMSE, fill = Analysis)) +
  geom_boxplot() +
  scale_x_discrete(breaks = meth, labels = meth_lab) +
  scale_fill_manual(values = meth_col) +
  theme_classic()
```

## Brier score

```{r brier}
brier <- purrr::map_dfr(results, function(.i){purrr::map_dfc(.i[,-c(1:2)], ~{mean((.x - .i$Y_true)^2)})}) %>% 
  tidyr::pivot_longer(cols = everything(), names_to = "Method", values_to = "Brier") %>% 
  mutate(Analysis = case_when(stringr::str_detect(Method, "log")~"FLR", TRUE~"RF"),
         Method = factor(Method, levels = meth, labels = meth_lab, ordered = TRUE)
        )

brier %>% 
  ggplot(aes(x = Method, y = Brier, fill = Analysis)) +
  geom_boxplot() +
  scale_x_discrete(breaks = meth, labels = meth_lab) +
  scale_fill_manual(values = meth_col) +
  theme_classic()
```
## AUC

```{r auc}
# # actual code switched of because of run time
# auc <- purrr::map_dfr(
#   results, function(.i){
#     purrr::map_dfc(
#       .i[,-c(1:2)], ~{
#         pROC::roc(.i$Y_true, .x) %>% .$auc %>% as.numeric()})}) %>% 
#   tidyr::pivot_longer(cols = everything(), names_to = "Method", values_to = "AUC") %>% 
#   mutate(Analysis = case_when(stringr::str_detect(Method, "log")~"FLR", TRUE~"RF"),
#          Method = factor(Method, levels = c(meth))
#         )
# saveRDS(auc, file = "auc.RDS")
auc <- readRDS("Results/auc.RDS")

auc %>% 
  ggplot(aes(x = Method, y = AUC, fill = Analysis)) +
  geom_boxplot() +
  scale_x_discrete(breaks = meth, labels = meth_lab) +
  scale_fill_manual(values = meth_col) +
  theme_classic()
```

```{r MAPE, eval=FALSE, include=FALSE}
# MAPE <- purrr::map_dfr(results, function(.i){purrr::map_dfc(.i[,-c(1:2)], ~{mean(abs((.i$Y_prob-.x)/.i$Y_prob * 100)) * 100})}) %>% 
#   tidyr::pivot_longer(cols = everything(), names_to = "Method", values_to = "MAPE") %>% 
#   mutate(Analysis = case_when(stringr::str_detect(Method, "log")~"FLR", TRUE~"RF"),
#          Method = factor(Method, levels = c(meth))
#         )
# 
# MAPE %>% 
#   ggplot(aes(x = Method, y = MAPE, fill = Analysis)) +
#   geom_boxplot() +
#   scale_x_discrete(breaks = meth, labels = meth_lab) +
#   scale_fill_manual(values = meth_col) +
#   theme_classic()
```


## Combine performance measures

```{r combine}
perf_wide <- cali %>% 
  cbind(AUC = auc$AUC) %>% 
  cbind(RMSE = rmse$RMSE) %>% 
  cbind(Brier = brier$Brier)

perf_long <- perf_wide %>% 
  tidyr::pivot_longer(cols = everything()[-c(1:2)]) %>% 
  mutate(Method = stringr::str_remove(Method, "([+])/"))

ggplot(perf_long, aes(x = Method, y = value, fill = Analysis)) +
  geom_boxplot() +
  scale_x_discrete(labels = meth_lab) +
  facet_wrap(~name, scales = "free") +
  coord_flip() +
  theme_classic()

```

# Table

## Average performance

```{r average}
perf_wide %>% 
  group_by(Method) %>% 
  summarise(across(everything()[-c(1:2)], mean)) # %>%
  # write.table(file = "table_perf.csv", sep = ",")
```

