---
title: "Real-time imputation SIG project"
output:
  html_document:
    df_print: paged
---

# Data Generating Mechanism

We will use a prediction model with: 

- 1 binary outcome ($Y$),
- 2 binary predictors ($X_1$, $X_2$),
- 2 continuous predictors ($X_3$, $X_4$).

Our sample will include at least these 5 variables too.

**Q: Do we want extra 'support' variables ($Z$) in our sample that are not included in the prediction model?**

```{r setup, message = FALSE, warning = FALSE, include = FALSE}
# environment
library("mvtnorm")
library("dplyr")

# data
load("./Data/varcov.RData")

# functions
source("./R/DGM.R")
```


```{r}
# let's generate some data, using these parameters
set.seed(11)
n <- 10000

# we'll the SMART data to define the relations between predictors
ggcorrplot::ggcorrplot(cov2cor(varcov), hc.order = TRUE, type = "lower", lab = TRUE)

# generate the data
dat <- sample_predictors(n)
dat <- dat %>% cbind(Y = compute_outcome(.), .)
glimpse(dat)

# test
mod1 <- glm(Y ~ ., family = "binomial", data = dat)
summary(mod1)
y_pred <- round(mod1$fitted.values)
mean(dat$Y==y_pred)
prob <- predict(mod1)
dat <- cbind(dat, prob=prob)
pROC::roc(Y~prob, data = dat)
```

